### ISSUE TITLE
Features Checklist

### ISSUE THREAD

**Issue by WizArdZ3658** [WizArdZ3658/Bank-Branches-Frontend#2]
- [x] User should be able to search by text for the banks, across all the fields.
- [x] As I type in the search area, the table should be dynamically filtered (client-side filtering).
- [x] The app should list and search for banks that are fetched from the API developed.
- [x] Bank search screen which would show a list of banks.
- [x] There would be no search button.
- [x] Pagination for the results of the search, the user should be able to select page size.
- [x] Mark some banks as favourites. 
- [x] View banks that were marked as favourites (favourites should persist state even if the website is refreshed or reloaded).
- [x] API calls should be cached.
- [x] Your application should be deployed to Heroku (Netlify better).
- [x] There should be a dropdown for cities (just put in 5 cities in there) and there is a search bar.
- [x] Clicking on bank name would redirect to a bank page, with a route like banks/{bankid} that displays the details of the bank

**Comment by WizArdZ3658** [comment]
All features have been successfully implemented ! :)
